import { FeedConfig } from "../../types/feed";

export const feeds: FeedConfig[] = [
  // ===== AI =====

  {
    source: "OpenAI News",
    url: "https://openai.com/news/rss.xml",
    category: "ai",
    skills: ["ai", "llm", "agents", "api"],
    quality: "official",
    minScore: 65,
  },
  {
    source: "Google AI Blog",
    url: "https://blog.google/technology/ai/rss/",
    category: "ai",
    skills: ["ai", "gemini", "research", "machine-learning"],
    quality: "official",
    minScore: 65,
  },
  {
    source: "DeepMind",
    url: "https://deepmind.google/blog/rss.xml",
    category: "ai",
    skills: ["ai", "research", "reasoning"],
    quality: "official",
    minScore: 65,
  },
  {
    source: "Hugging Face Blog",
    url: "https://huggingface.co/blog/feed.xml",
    category: "ai",
    skills: ["ai", "machine-learning", "open-source-models"],
    quality: "official",
    minScore: 65,
  },
  {
    source: "Simon Willison",
    url: "https://simonwillison.net/atom/everything/",
    category: "ai",
    skills: ["llm", "agents", "ai-engineering"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "Latent Space",
    url: "https://www.latent.space/feed",
    category: "ai",
    skills: ["llm", "agents", "ai-engineering"],
    quality: "engineering",
    minScore: 70,
  },
  // [+] AI engineering / tooling
  {
    source: "Weights & Biases Blog",
    url: "https://wandb.ai/fully-connected/rss.xml",
    category: "ai",
    skills: ["ai", "mlops", "experiment-tracking", "machine-learning"],
    quality: "engineering",
    minScore: 65,
  },
  {
    source: "LlamaIndex Blog",
    url: "https://medium.com/feed/llamaindex-blog",
    category: "ai",
    skills: ["llm", "rag", "agents", "ai-engineering"],
    quality: "engineering",
    minScore: 65,
  },
  // Arxiv CS.AI: feed cực kỳ noisy (100+ paper/ngày). minScore 85 để chỉ lấy
  // những paper được HN/cộng đồng chú ý nhiều. Theo dõi sát tuần đầu sau deploy.
  {
    source: "Arxiv CS.AI",
    url: "https://rss.arxiv.org/rss/cs.AI",
    category: "ai",
    skills: ["ai", "research", "machine-learning", "deep-learning"],
    quality: "official",
    minScore: 60,
  },

  // ===== Hacker News =====

  {
    source: "Hacker News",
    url: "https://hnrss.org/frontpage?points=100",
    category: "general",
    skills: ["startup", "engineering", "programming", "ai"],
    quality: "discussion",
    minScore: 65,
    minComments: 20,
  },
  {
    source: "Hacker News AI",
    url: "https://hnrss.org/newest?q=AI",
    category: "ai",
    skills: ["ai", "llm", "engineering"],
    quality: "discussion",
    minScore: 65,
    minComments: 20,
  },
  {
    source: "Hacker News LLM",
    url: "https://hnrss.org/newest?q=LLM",
    category: "ai",
    skills: ["llm", "agents", "engineering"],
    quality: "discussion",
    minScore: 65,
    minComments: 20,
  },

  // ===== Backend / Architecture =====

  {
    source: "Node.js Blog",
    url: "https://nodejs.org/en/feed/blog.xml",
    category: "backend",
    skills: ["nodejs", "javascript", "backend", "runtime"],
    quality: "official",
    minScore: 65,
  },
  {
    source: "Node.js Vulnerabilities",
    url: "https://nodejs.org/en/feed/vulnerability.xml",
    category: "security",
    skills: ["nodejs", "security", "runtime"],
    quality: "official",
    minScore: 70,
  },
  {
    source: "Bun Blog",
    url: "https://bun.com/rss.xml",
    category: "backend",
    skills: ["bun", "javascript", "runtime"],
    quality: "official",
    minScore: 65,
  },
  {
    source: "Deno Blog",
    url: "https://deno.com/feed",
    category: "backend",
    skills: ["deno", "typescript", "runtime"],
    quality: "official",
    minScore: 65,
  },
  {
    source: "GitHub Blog",
    url: "https://github.blog/feed/",
    category: "general",
    skills: ["github", "open-source", "developer-tools"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "GitHub Engineering",
    url: "https://github.blog/engineering/feed/",
    category: "backend",
    skills: ["architecture", "developer-tools"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "InfoQ Architecture",
    url: "https://feed.infoq.com/architecture",
    category: "backend",
    skills: ["architecture", "system-design"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "Netflix TechBlog",
    url: "https://netflixtechblog.com/feed",
    category: "backend",
    skills: ["distributed-systems", "performance"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "Slack Engineering",
    url: "https://slack.engineering/feed",
    category: "backend",
    skills: ["backend", "architecture", "performance"],
    quality: "engineering",
    minScore: 70,
  },
  // [+] Go và Rust — gap lớn trong danh sách backend
  {
    source: "Go Blog",
    url: "https://go.dev/blog/feed.atom",
    category: "backend",
    skills: ["go", "backend", "runtime", "performance"],
    quality: "official",
    minScore: 70,
  },
  {
    source: "This Week in Rust",
    url: "https://this-week-in-rust.org/rss.xml",
    category: "backend",
    skills: ["rust", "systems-programming", "performance", "backend"],
    quality: "engineering",
    minScore: 70,
  },

  // ===== Database =====

  {
    source: "Planet PostgreSQL",
    url: "https://planet.postgresql.org/rss20.xml",
    category: "backend",
    skills: ["postgresql", "database", "performance"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "Postgres Weekly",
    url: "https://postgresweekly.com/rss/",
    category: "backend",
    skills: ["postgresql", "query-plan", "database"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "MongoDB Engineering",
    url: "https://www.mongodb.com/company/blog/rss",
    category: "backend",
    skills: ["mongodb", "database", "distributed-systems"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "Redis Blog",
    url: "https://redis.io/blog/feed/",
    category: "backend",
    skills: ["redis", "cache", "database"],
    quality: "engineering",
    minScore: 70,
  },

  // ===== DevOps / SRE =====

  {
    source: "Cloudflare Blog",
    url: "https://blog.cloudflare.com/rss/",
    category: "devops",
    skills: ["cloudflare", "security", "edge"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "Cloudflare Changelog",
    url: "https://developers.cloudflare.com/changelog/rss.xml",
    category: "devops",
    skills: ["cloudflare", "deployment"],
    quality: "official",
    minScore: 65,
  },
  {
    source: "AWS Architecture Blog",
    url: "https://aws.amazon.com/blogs/architecture/feed/",
    category: "devops",
    skills: ["aws", "scaling", "reliability"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "SRE Weekly",
    url: "https://sreweekly.com/feed/",
    category: "devops",
    skills: ["sre", "monitoring", "reliability", "postmortem"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "HashiCorp Blog",
    url: "https://www.hashicorp.com/blog/feed.xml",
    category: "devops",
    skills: ["terraform", "vault", "infrastructure"],
    quality: "engineering",
    minScore: 70,
  },
  // [+] Observability gap
  {
    source: "Grafana Blog",
    url: "https://grafana.com/blog/index.xml",
    category: "devops",
    skills: ["observability", "monitoring", "grafana", "metrics"],
    quality: "engineering",
    minScore: 65,
  },

  // ===== Mobile =====
  // [+] category "mobile" trước đây không có feed nào

  {
    source: "Swift Blog",
    url: "https://www.swift.org/atom.xml",
    category: "mobile",
    skills: ["swift", "ios", "apple", "mobile"],
    quality: "official",
    minScore: 70,
    sourceBoost: 20,
  },
  {
    source: "Android Developers Blog",
    url: "https://android-developers.googleblog.com/feeds/posts/default",
    category: "mobile",
    skills: ["android", "kotlin", "mobile", "google"],
    quality: "official",
    minScore: 65,
    sourceBoost: 20,
  },
  {
    source: "Flutter Blog",
    url: "https://medium.com/flutter/feed",
    category: "mobile",
    skills: ["flutter", "dart", "mobile", "cross-platform"],
    quality: "official",
    minScore: 65,
    sourceBoost: 20,
  },
  {
    source: "Reddit iOSProgramming",
    url: "https://www.reddit.com/r/iOSProgramming/hot/.rss",
    category: "mobile",
    skills: ["ios", "swift", "xcode", "mobile"],
    quality: "discussion",
    minScore: 65,
    minComments: 20,
  },
  {
    source: "Reddit AndroidDev",
    url: "https://www.reddit.com/r/androiddev/hot/.rss",
    category: "mobile",
    skills: ["android", "kotlin", "jetpack-compose", "mobile"],
    quality: "discussion",
    minScore: 65,
    minComments: 20,
  },

  // ===== Career =====
  // [+] category "career" trước đây không có feed nào
  // Lưu ý: Lenny's Newsletter và The Pragmatic Engineer là Substack —
  // kiểm tra thực tế xem feed có bị paywall cắt không, nếu có thì xóa.

  {
    source: "Lenny's Newsletter",
    url: "https://www.lennysnewsletter.com/feed",
    category: "career",
    skills: ["product", "career", "engineering-management", "productivity"],
    quality: "engineering",
    minScore: 70,
    sourceBoost: 20,
  },
  {
    source: "The Pragmatic Engineer",
    url: "https://newsletter.pragmaticengineer.com/feed",
    category: "career",
    skills: ["career", "engineering-management", "salary", "big-tech"],
    quality: "engineering",
    minScore: 75,
    sourceBoost: 20,
  },
  {
    source: "Will Larson (Lethain)",
    url: "https://lethain.com/feeds.xml",
    category: "career",
    skills: ["career", "staff-engineer", "engineering-leadership", "ic-track"],
    quality: "engineering",
    minScore: 70,
    sourceBoost: 20,
  },

  // ===== Security =====

  {
    source: "Google Project Zero",
    url: "https://googleprojectzero.blogspot.com/feeds/posts/default?alt=rss",
    category: "security",
    skills: ["security", "vulnerability", "exploit-analysis"],
    quality: "official",
    minScore: 70,
  },
  // [+] Security gap — chỉ có Project Zero và Node.js Vuln là quá ít
  {
    source: "Krebs on Security",
    url: "https://krebsonsecurity.com/feed/",
    category: "security",
    skills: ["security", "cybercrime", "vulnerability", "breach"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "Schneier on Security",
    url: "https://www.schneier.com/feed/atom/",
    category: "security",
    skills: ["security", "cryptography", "privacy", "policy"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "CISA Advisories",
    url: "https://www.cisa.gov/uscert/ncas/alerts.xml",
    category: "security",
    skills: ["security", "vulnerability", "cve", "advisory"],
    quality: "official",
    minScore: 75,
  },

  // ===== Linux / VPS =====

  {
    source: "Selfh.st",
    url: "https://selfh.st/rss/",
    category: "devops",
    skills: ["docker", "linux", "self-hosted", "vps"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "LWN",
    url: "https://lwn.net/headlines/rss",
    category: "devops",
    skills: ["linux", "kernel", "system"],
    quality: "engineering",
    minScore: 75,
  },

  // ===== Community =====

  {
    source: "Reddit LocalLLaMA",
    url: "https://www.reddit.com/r/LocalLLaMA/hot/.rss",
    category: "ai",
    skills: ["llm", "agents", "open-source-models"],
    quality: "discussion",
    minScore: 65,
    minComments: 30,
  },
  {
    source: "Reddit MachineLearning",
    url: "https://www.reddit.com/r/MachineLearning/hot/.rss",
    category: "ai",
    skills: ["machine-learning", "research"],
    quality: "discussion",
    minScore: 65,
    minComments: 20,
  },
  {
    source: "Reddit Programming",
    url: "https://www.reddit.com/r/programming/hot/.rss",
    category: "backend",
    skills: ["programming", "system-design"],
    quality: "discussion",
    minScore: 65,
    minComments: 30,
  },
  {
    source: "Reddit Backend",
    url: "https://www.reddit.com/r/backend/hot/.rss",
    category: "backend",
    skills: ["backend", "architecture", "database"],
    quality: "discussion",
    minScore: 65, // [fix] tăng từ 60 → 65 để đồng nhất với các Reddit khác
    minComments: 20,
  },
  {
    source: "Reddit PostgreSQL",
    url: "https://www.reddit.com/r/PostgreSQL/hot/.rss",
    category: "backend",
    skills: ["postgresql", "query-plan", "replication"],
    quality: "discussion",
    minScore: 65, // [fix] tăng từ 60 → 65
    minComments: 20,
  },
  {
    source: "Reddit DevOps",
    url: "https://www.reddit.com/r/devops/hot/.rss",
    category: "devops",
    skills: ["devops", "cloud", "monitoring"],
    quality: "discussion",
    minScore: 65,
    minComments: 20,
  },
  {
    source: "Reddit SelfHosted",
    url: "https://www.reddit.com/r/selfhosted/hot/.rss",
    category: "devops",
    skills: ["docker", "linux", "self-hosted"],
    quality: "discussion",
    minScore: 65,
    minComments: 20,
  },
  {
    source: "Reddit SysAdmin",
    url: "https://www.reddit.com/r/sysadmin/hot/.rss",
    category: "devops",
    skills: ["linux", "infrastructure", "operations"],
    quality: "discussion",
    minScore: 65,
    minComments: 20,
  },

  // ===== Frontend =====

  {
    source: "JavaScript Weekly",
    url: "https://javascriptweekly.com/rss",
    category: "frontend",
    skills: ["javascript", "typescript", "web"],
    quality: "engineering",
    minScore: 75,
  },
  {
    source: "Frontend Focus",
    url: "https://frontendfoc.us/rss",
    category: "frontend",
    skills: ["frontend", "web", "javascript"],
    quality: "engineering",
    minScore: 75,
  },
  {
    source: "Web.dev",
    url: "https://web.dev/static/blog/feed.xml",
    category: "frontend",
    skills: ["web-performance", "frontend", "browser"],
    quality: "official",
    minScore: 70,
  },
  {
    source: "Chrome Developers",
    url: "https://developer.chrome.com/blog/feed.xml",
    category: "frontend",
    skills: ["browser", "web-platform", "performance"],
    quality: "official",
    minScore: 70,
  },
  {
    source: "Vercel Blog",
    url: "https://vercel.com/blog/rss.xml",
    category: "frontend",
    skills: ["nextjs", "frontend", "deployment"],
    quality: "engineering",
    minScore: 70,
    sourceBoost: 20,
  },
  {
    source: "Next.js Blog",
    url: "https://nextjs.org/feed.xml",
    category: "frontend",
    skills: ["nextjs", "react", "frontend"],
    quality: "official",
    minScore: 70,
    sourceBoost: 20,
  },
  {
    source: "React Blog",
    url: "https://react.dev/rss.xml",
    category: "frontend",
    skills: ["react", "frontend", "javascript"],
    quality: "official",
    minScore: 70,
    sourceBoost: 20,
  },
  {
    source: "Vue.js Blog",
    url: "https://blog.vuejs.org/feed.rss",
    category: "frontend",
    skills: ["vue", "frontend", "javascript"],
    quality: "official",
    minScore: 70,
    sourceBoost: 20,
  },
  {
    source: "Angular Blog",
    url: "https://blog.angular.dev/feed",
    category: "frontend",
    skills: ["angular", "typescript", "frontend"],
    quality: "official",
    minScore: 70,
    sourceBoost: 20,
  },
  {
    source: "Tailwind CSS Blog",
    url: "https://tailwindcss.com/feeds/feed.xml",
    category: "frontend",
    skills: ["tailwind", "css", "frontend"],
    quality: "official",
    minScore: 70,
    sourceBoost: 20,
  },
  // [removed] CSS-Tricks — ngừng đăng bài mới từ cuối 2023
  {
    source: "Smashing Magazine",
    url: "https://www.smashingmagazine.com/feed/",
    category: "frontend",
    skills: ["frontend", "css", "ux", "web"],
    quality: "engineering",
    minScore: 75,
  },
  {
    source: "Nielsen Norman Group",
    url: "https://www.nngroup.com/feed/rss",
    category: "frontend",
    skills: ["ux", "ui", "product-design"],
    quality: "engineering",
    minScore: 75,
  },
  {
    source: "Dev.to Backend",
    url: "https://dev.to/feed/tag/backend",
    category: "backend",
    skills: ["backend", "database", "node", "python", "go"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "Dev.to Architecture",
    url: "https://dev.to/feed/tag/architecture",
    category: "backend",
    skills: ["architecture", "system-design", "microservices"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "Dev.to Programming",
    url: "https://dev.to/feed/tag/programming",
    category: "backend",
    skills: ["programming", "best-practices", "code-quality"],
    quality: "engineering",
    minScore: 70,
  },

  // ===== System Design & Tutorials =====

  // [removed] ByteByteGo — Substack paywall cắt nội dung, model nhận bài cụt
  {
    source: "DigitalOcean Blog",
    url: "https://www.digitalocean.com/blog/rss/",
    category: "devops",
    skills: ["vps", "linux", "docker", "cloud", "aws", "deployment"],
    quality: "engineering",
    minScore: 65,
  },
  {
    source: "Node Weekly",
    url: "https://nodeweekly.com/rss",
    category: "backend",
    skills: ["nodejs", "javascript", "backend", "utilities"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "LogRocket Blog",
    url: "https://blog.logrocket.com/feed/",
    category: "backend",
    skills: ["programming", "frontend", "backend", "utilities", "orm"],
    quality: "engineering",
    minScore: 70,
  },

  // ===== Database & ORM =====

  {
    source: "Prisma Blog",
    url: "https://www.prisma.io/blog/rss.xml",
    category: "backend",
    skills: ["orm", "prisma", "database", "typescript", "nodejs", "postgresql"],
    quality: "official",
    minScore: 70,
  },
  {
    source: "MikroORM Releases",
    url: "https://github.com/mikro-orm/mikro-orm/releases.atom",
    category: "backend",
    skills: ["orm", "mikro-orm", "database", "typescript"],
    quality: "official",
    minScore: 65,
  },
  {
    source: "Drizzle ORM Releases",
    url: "https://github.com/drizzle-team/drizzle-orm/releases.atom",
    category: "backend",
    skills: ["orm", "drizzle", "database", "typescript"],
    quality: "official",
    minScore: 65,
  },
  // [removed] PlanetScale Blog — đóng free tier, blog gần như không còn cập nhật
  {
    source: "Supabase Blog",
    url: "https://supabase.com/feed.xml",
    category: "backend",
    skills: ["database", "postgresql", "sql", "supabase", "backend"],
    quality: "official",
    minScore: 70,
  },
  {
    source: "Timescale Blog",
    url: "https://www.timescale.com/blog/rss/",
    category: "backend",
    skills: ["database", "postgresql", "sql", "time-series", "query-optimization"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "TigerBeetle Blog",
    url: "https://tigerbeetle.com/blog/atom.xml",
    category: "backend",
    skills: ["database", "distributed-systems", "performance", "ledger", "storage-engine"],
    quality: "engineering",
    minScore: 70,
  },

  // ===== Cộng đồng Việt Nam & châu Á =====

  {
    source: "Viblo",
    url: "https://viblo.asia/rss",
    category: "backend",
    skills: ["programming", "backend", "frontend", "devops", "cloud", "database"],
    quality: "engineering",
    minScore: 65, // [fix] tăng từ 60 → 65, chất lượng bài Viblo không đồng đều
    minComments: 5,
  },
  {
    source: "Ehkoo",
    url: "https://ehkoo.com/rss.xml",
    category: "frontend",
    skills: ["frontend", "javascript", "react", "web"],
    quality: "engineering",
    minScore: 65,
  },
  // [removed] Juno_okyo — Blogger cá nhân, không còn active ổn định
  {
    source: "Zenn",
    url: "https://zenn.dev/feed",
    category: "other",
    skills: ["programming", "web", "learning", "tech"],
    quality: "discussion",
    minScore: 60,
  },
  {
    source: "Qiita",
    url: "https://qiita.com/popular-items/feed.atom",
    category: "other",
    skills: ["programming", "web", "learning", "tech"],
    quality: "discussion",
    minScore: 60,
  },
  {
    source: "Kakao Tech",
    url: "https://tech.kakao.com/feed/",
    category: "backend",
    skills: ["programming", "web", "engineering", "tech"],
    quality: "official",
    minScore: 65,
  },
  {
    source: "Toss Tech",
    url: "https://toss.tech/rss.xml",
    category: "backend",
    skills: ["backend", "web", "architecture", "fintech"],
    quality: "official",
    minScore: 65,
  },
  // [removed] VnExpress So Hoa — consumer tech news, ít technical insight cho dev audience
  // [removed] Tinhte — tương tự VnExpress, không phù hợp với dev audience
];
