import { type FeedConfig } from "../../types/feed";

export const feeds: FeedConfig[] = [
  // Core developer blogs
  {
    source: "Hacker News",
    url: "https://hnrss.org/frontpage?points=100",
    category: "general",
    skills: ["startup", "engineering", "programming", "ai"],
    quality: "discussion",
    minScore: 65,
    minComments: 20,
  },
  {
    source: "Dev.to",
    url: "https://dev.to/feed",
    category: "general",
    skills: ["javascript", "typescript", "web", "backend"],
    quality: "low-signal",
    minScore: 83,
  },
  {
    source: "OpenAI News",
    url: "https://openai.com/news/rss.xml",
    category: "ai",
    skills: ["ai", "llm", "agents", "api"],
    quality: "official",
    minScore: 65,
  },
  {
    source: "Hugging Face Blog",
    url: "https://huggingface.co/blog/feed.xml",
    category: "ai",
    skills: ["ai", "machine-learning", "open-source-models"],
    quality: "official",
    minScore: 65,
  },

  // Backend / Runtime
  {
    source: "Node.js Blog",
    url: "https://nodejs.org/en/feed/blog.xml",
    category: "backend",
    skills: ["nodejs", "javascript", "backend", "runtime"],
    quality: "official",
    minScore: 65,
  },
  {
    source: "Node.js Vulnerabilities",
    url: "https://nodejs.org/en/feed/vulnerability.xml",
    category: "security",
    skills: ["nodejs", "security", "backend", "runtime"],
    quality: "official",
    minScore: 70,
  },

  // General developer / engineering
  {
    source: "GitHub Blog",
    url: "https://github.blog/feed/",
    category: "general",
    skills: ["github", "open-source", "developer-tools", "backend"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "InfoQ Architecture",
    url: "https://feed.infoq.com/architecture",
    category: "backend",
    skills: ["architecture", "backend", "system-design"],
    quality: "engineering",
    minScore: 70,
  },

  // Production engineering / security
  {
    source: "Netflix TechBlog",
    url: "https://netflixtechblog.com/feed",
    category: "backend",
    skills: ["architecture", "distributed-systems", "performance", "backend"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "Cloudflare Blog",
    url: "https://blog.cloudflare.com/rss/",
    category: "devops",
    skills: ["cloudflare", "edge", "security", "performance"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "AWS Architecture Blog",
    url: "https://aws.amazon.com/blogs/architecture/feed/",
    category: "devops",
    skills: ["aws", "architecture", "scaling", "reliability"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "Google Project Zero",
    url: "https://googleprojectzero.blogspot.com/feeds/posts/default?alt=rss",
    category: "security",
    skills: ["security", "vulnerability", "root-cause", "exploit-analysis"],
    quality: "official",
    minScore: 70,
  },

  // Frontend / UX / UI / Weekly Newsletters
  {
    source: "Nielsen Norman Group",
    url: "https://www.nngroup.com/feed/rss",
    category: "other",
    skills: ["ux", "ui", "product-design", "frontend"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "Front-End Front",
    url: "https://frontendfront.com/feed.xml",
    category: "frontend",
    skills: ["frontend", "web", "css", "html", "javascript"],
    quality: "low-signal",
    minScore: 83,
  },
  {
    source: "CSS-Tricks",
    url: "https://css-tricks.com/feed/",
    category: "frontend",
    skills: ["css", "frontend", "web", "design"],
    quality: "low-signal",
    minScore: 83,
  },
  {
    source: "CSS Weekly",
    url: "https://css-weekly.com/feed/",
    category: "frontend",
    skills: ["css", "frontend", "web", "design"],
    quality: "low-signal",
    minScore: 83,
  },
  {
    source: "JavaScript Weekly",
    url: "https://javascriptweekly.com/rss",
    category: "frontend",
    skills: ["javascript", "typescript", "web"],
    quality: "low-signal",
    minScore: 83,
  },
  {
    source: "Node Weekly",
    url: "https://nodeweekly.com/rss",
    category: "backend",
    skills: ["nodejs", "javascript", "backend"],
    quality: "low-signal",
    minScore: 83,
  },

  // DevOps / Cloud / Edge
  {
    source: "Cloudflare Changelog",
    url: "https://developers.cloudflare.com/changelog/rss.xml",
    category: "devops",
    skills: ["cloudflare", "edge", "security", "deployment"],
    quality: "official",
    minScore: 65,
  },

  // Community signal - chỉ dùng để bắt trend, không coi là nguồn chính thức
  {
    source: "Reddit Node",
    url: "https://www.reddit.com/r/node/hot/.rss",
    category: "backend",
    skills: ["nodejs", "javascript", "backend"],
    quality: "discussion",
    minScore: 60,
    minComments: 20,
  },
  {
    source: "Reddit WebDev",
    url: "https://www.reddit.com/r/webdev/hot/.rss",
    category: "frontend",
    skills: ["web", "frontend", "fullstack"],
    quality: "discussion",
    minScore: 60,
    minComments: 20,
  },
  {
    source: "Reddit Backend",
    url: "https://www.reddit.com/r/Backend/hot/.rss",
    category: "backend",
    skills: ["backend", "architecture", "database", "system-design"],
    quality: "discussion",
    minScore: 60,
    minComments: 20,
  },
  {
    source: "Reddit PostgreSQL",
    url: "https://www.reddit.com/r/PostgreSQL/hot/.rss",
    category: "backend",
    skills: ["postgresql", "query-plan", "index", "replication"],
    quality: "discussion",
    minScore: 60,
    minComments: 20,
  },
  {
    source: "Reddit Database",
    url: "https://www.reddit.com/r/Database/hot/.rss",
    category: "backend",
    skills: ["database", "data-architecture", "transactions", "performance"],
    quality: "discussion",
    minScore: 60,
    minComments: 20,
  },
  {
    source: "Reddit Programming",
    url: "https://www.reddit.com/r/programming/hot/.rss",
    category: "backend",
    skills: ["programming", "system-design", "runtime", "performance"],
    quality: "discussion",
    minScore: 65,
    minComments: 30,
  },
  {
    source: "Reddit RemoteITJobs",
    url: "https://www.reddit.com/r/RemoteITJobs/hot/.rss",
    category: "career",
    skills: ["career", "remote", "jobs", "it"],
    quality: "low-signal",
    minScore: 80,
  },
  {
    source: "Reddit linux4noobs",
    url: "https://www.reddit.com/r/linux4noobs/hot/.rss",
    category: "devops",
    skills: ["linux", "bash", "sysadmin", "devops"],
    quality: "low-signal",
    minScore: 85,
  },

  // StackOverflow - câu hỏi kỹ thuật mới, không phải news chính thống
  {
    source: "StackOverflow Node.js",
    url: "https://stackoverflow.com/feeds/tag?tagnames=node.js&sort=newest",
    category: "backend",
    skills: ["nodejs", "javascript", "backend"],
    quality: "low-signal",
    minScore: 80,
  },

  {
    source: "MongoDB Engineering Blog",
    url: "https://www.mongodb.com/company/blog/channel/engineering-blog",
    category: "backend",
    skills: ["mongodb", "database", "distributed-systems"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "PostgreSQL News",
    url: "https://www.postgresql.org/about/newsarchive/",
    category: "backend",
    skills: ["postgresql", "database", "sql"],
    quality: "official",
    minScore: 65,
  },
  {
    source: "Redis Blog",
    url: "https://redis.io/blog/",
    category: "backend",
    skills: ["redis", "cache", "database"],
    quality: "engineering",
    minScore: 70,
  },
  {
    source: "Percona Blog",
    url: "https://www.percona.com/blog/feed/",
    category: "backend",
    skills: ["database", "mysql", "postgresql", "performance"],
    quality: "engineering",
    minScore: 70,
  },
];
